#!/usr/bin/python

iso_codes = {"om" : "Oromo",
 "ab" : "Abkhazian",
 "aa" : "Afar",
 "af" : "Afrikaans",
 "sq" : "Albanian",
 "am" : "Amharic",
 "ar" : "Arabic",
 "hy" : "Armenian",
 "as" : "Assamese",
 "ay" : "Aymara",
 "az" : "Azerbaijani",
 "ba" : "Bashkir",
 "eu" : "Basque",
 "bn" : "Bengali",
 "dz" : "Bhutani",
 "bh" : "Bihari",
 "bi" : "Bislama",
 "br" : "Breton",
 "bg" : "Bulgarian",
 "my" : "Burmese",
 "be" : "Byelorussian",
 "km" : "Cambodian",
 "ca" : "Catalan",
 "zh" : "Chinese",
 "co" : "Corsican",
 "hr" : "Croatian",
 "cs" : "Czech",
 "da" : "Danish",
 "nl" : "Dutch",
 "en" : "English",
 "eo" : "Esperanto",
 "et" : "Estonian",
 "fo" : "Faeroese",
 "fj" : "Fiji",
 "fi" : "Finnish",
 "fr" : "French",
 "fy" : "Frisian",
 "gl" : "Galician",
 "ka" : "Georgian",
 "de" : "German",
 "el" : "Greek",
 "kl" : "Greenlandic",
 "gn" : "Guarani",
 "gu" : "Gujarati",
 "ha" : "Hausa",
 "he" : "Hebrew",
 "hi" : "Hindi",
 "hu" : "Hungarian",
 "is" : "Icelandic",
 "id" : "Indonesian",
 "ia" : "Interlingua",
 "ie" : "Interlingue",
 "ik" : "Inupiak",
 "iu" : "Inuktitut",
 "ga" : "Irish",
 "it" : "Italian",
 "ja" : "Japanese",
 "jw" : "Javanese",
 "kn" : "Kannada",
 "ks" : "Kashmiri",
 "kk" : "Kazakh",
 "rw" : "Kinyarwanda",
 "ky" : "Kirghiz",
 "rn" : "Kirundi",
 "ko" : "Korean",
 "ku" : "Kurdish",
 "lo" : "Laothian",
 "la" : "Latin",
 "lv" : "LatvianLettish",
 "ln" : "Lingala",
 "lt" : "Lithuanian",
 "mk" : "Macedonian",
 "mg" : "Malagasy",
 "ms" : "Malay",
 "ml" : "Malayalam",
 "mt" : "Maltese",
 "mi" : "Maori",
 "mr" : "Marathi",
 "mo" : "Moldavian",
 "mn" : "Mongolian",
 "na" : "Nauru",
 "ne" : "Nepali",
 "no" : "Norwegian",
 "oc" : "Occitan",
 "or" : "Oriya",
 "ps" : "PashtoPushto",
 "fa" : "Persian",
 "pl" : "Polish",
 "pt" : "Portuguese",
 "pa" : "Punjabi",
 "qu" : "Quechua",
 "rm" : "RhaetoRomance",
 "ro" : "Romanian",
 "ru" : "Russian",
 "sm" : "Samoan",
 "sg" : "Sangro",
 "sa" : "Sanskrit",
 "gd" : "Scots Gaelic",
 "sr" : "Serbian",
 "sh" : "SerboCroatian",
 "st" : "Sesotho",
 "tn" : "Setswana",
 "sn" : "Shona",
 "sd" : "Sindhi",
 "si" : "Singhalese",
 "ss" : "Siswati",
 "sk" : "Slovak",
 "sl" : "Slovenian",
 "so" : "Somali",
 "es" : "Spanish",
 "su" : "Sudanese",
 "sw" : "Swahili",
 "sv" : "Swedish",
 "tl" : "Tagalog",
 "tg" : "Tajik",
 "ta" : "Tamil",
 "tt" : "Tatar",
 "te" : "Tegulu",
 "th" : "Thai",
 "bo" : "Tibetan",
 "ti" : "Tigrinya",
 "to" : "Tonga",
 "ts" : "Tsonga",
 "tr" : "Turkish",
 "tk" : "Turkmen",
 "tw" : "Twi",
 "ug" : "Uigur",
 "uk" : "Ukrainian",
 "ur" : "Urdu",
 "uz" : "Uzbek",
 "vi" : "Vietnamese",
 "vo" : "Volapuk",
 "cy" : "Welch",
 "wo" : "Wolof",
 "xh" : "Xhosa",
 "yi" : "Yiddish",
 "yo" : "Yoruba",
 "za" : "Zhuang",
 "zu" : "Zulu"
}



def get_language_full_name(code):
    global iso_codes

    if (code in iso_codes):
        return iso_codes[code]
    else:
        return code

